name: Build with Wrapper JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: |
        cd LayoutOrchestrator
        chmod +x gradlew

    - name: Build with Gradle
      run: |
        cd LayoutOrchestrator
        ./gradlew assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: layout-orchestrator-apk
        path: LayoutOrchestrator/app/build/outputs/apk/release/*.apk
