name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip Project
        run: |
          unzip -o LayoutOrchestrator-final.zip -d ./workspace
          echo "Contents after unzip:"
          ls -R ./workspace | head -50

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release APK
        run: |
          # adjust path if needed depending on unzip result
          if [ -d "workspace/LayoutOrchestrator" ]; then
            cd workspace/LayoutOrchestrator
          elif [ -d "workspace/LayoutOrchestrator-final/LayoutOrchestrator" ]; then
            cd workspace/LayoutOrchestrator-final/LayoutOrchestrator
          else
            echo "❌ Could not find LayoutOrchestrator project after unzip"
            exit 1
          fi
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LayoutOrchestrator-APK
          path: '**/app/build/outputs/apk/release/*.apk'
