name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: |
        cd LayoutOrchestrator
        chmod +x gradlew

    - name: Create Gradle wrapper if needed
      run: |
        cd LayoutOrchestrator
        mkdir -p gradle/wrapper
        if [ ! -f "gradle/wrapper/gradle-wrapper.properties" ]; then
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.5-bin.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "networkTimeout=10000" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
        fi

    - name: Build with Gradle
      run: |
        cd LayoutOrchestrator
        ./gradlew assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: layout-orchestrator-apk
        path: LayoutOrchestrator/app/build/outputs/apk/release/*.apk
