name: Build Android APK from Unzipped Project

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Unzipped Project
        run: |
          echo "Checking contents of unzipped project"
          ls destination-folder/LayoutOrchestrator-final/
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release APK
        run: |
          cd destination-folder/LayoutOrchestrator-final
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LayoutOrchestrator-APK
          path: destination-folder/LayoutOrchestrator-final/app/build/outputs/apk/release/*.apk
