name: Generate and Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true

    - name: Make generator script executable
      run: |
        chmod +x .github/scripts/generate-full-project.sh

    - name: Generate Full Android Project
      run: |
        ./.github/scripts/generate-full-project.sh

    - name: Fix project structure
      run: |
        chmod +x .github/scripts/fix-project.sh
        ./.github/scripts/fix-project.sh

    - name: Commit and Push Generated Files
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Auto-generate project structure and fix gradlew" || echo "Nothing to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build Project
      run: |
        cd LayoutOrchestrator
        chmod +x gradlew
        ./gradlew assembleRelease --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: layout-orchestrator-apk
        path: LayoutOrchestrator/app/build/outputs/apk/release/*.apk
